version: '3.7'
services:
  squid:
    build: .
    image: nickadam/squidproxy:1
    environment:
      PASSWORDS_FILE: /run/secrets/passwords
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    secrets:
      - passwords
secrets:
  passwords:
    external: true
