version: '3.7'
services:
  squid:
    build: .
    image: reg.hcpss.org/library/squidproxy:v3.0.0
    environment:
      LDAP_HOST: ldaps://example.com
      LDAP_BASE: DC=example,DC=com
      LDAP_READ_USER: readuser@example.com
      LDAP_READ_PASS_FILE: /run/secrets/readuser_password
      LOCAL_NETS: |
        acl localnet src 172.18.0.0/24   # dev
        acl localnet src 172.19.0.0/24   # other net
    ports:
      - target: 80
        published: 8888
        protocol: tcp
        mode: host
    secrets:
      - readuser_password
secrets:
  readuser_password:
    external: true
