#!/bin/sh

# get LOCAL_NETS line
localnets_line=$(grep -n LOCAL_NETS /squid.conf | grep -o -e "[0-9]\+")

# write squid conf
cat /squid.conf \
  | sed "s/LDAP_HOST/$(echo $LDAP_HOST | sed 's/\//\\\//g')/" \
  | sed "s/LDAP_READ_USER/$LDAP_READ_USER/" \
  | sed "s/LDAP_READ_PASS_FILE/$(echo $LDAP_READ_PASS_FILE | sed 's/\//\\\//g')/" \
  | sed "s/LDAP_BASE/$LDAP_BASE/" > /squid_temp.conf
head -n $(($localnets_line-1)) /squid_temp.conf  > /etc/squid/squid.conf
echo "$LOCAL_NETS"                               >> /etc/squid/squid.conf
tail -n +$(($localnets_line+1)) /squid_temp.conf >> /etc/squid/squid.conf

# clear logs once a day
while true
do
  sleep 86400
  echo -n >/var/log/squid/access.log
  echo -n >/var/log/squid/cache.log
done &

# start squid in background
squid

# wait for log file
while [ ! -f /var/log/squid/access.log ]
do
  sleep 1
done

tail -f /var/log/squid/access.log
