#!/bin/sh

# set passwords by env var
if [ ! -z "$PASSWORDS" ]
then
  echo "$PASSWORDS" > /etc/squid/passwords
fi

# set passwords by env var secrets file
if [ ! -z "$PASSWORDS_FILE" ]
then
  cat "$PASSWORDS_FILE" > /etc/squid/passwords
fi

# clear logs once a day
while true
do
  sleep 86400
  echo -n >/var/log/squid/access.log
  echo -n >/var/log/squid/cache.log
done &

squid

# wait for log file
while [ ! -f /var/log/squid/access.log ]
do
  sleep 1
done

tail -f /var/log/squid/access.log
